services:
  express-api:
    build:
      context: ./server
    container_name: express-api
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - prometheus
      # - influxdb
    environment:
      - INFLUX_URL=https://us-east-1-1.aws.cloud2.influxdata.com
      - INFLUX_TOKEN=v_4V4M6inDq7zcgbwKkMpQoJGdccqXR3ZSDZ9f3U30U0-gwO7RB4R_Yu1T62m9x9ZNDIRHOnMXMK0ji1O0F_sA==
      - ORG=MainOrg
      - BUCKET=myBucket
      - INFLUX_ORG_ID=4b0bdb9cb7ea7c6c

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27018:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - ./mongo_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_X_FRAME_OPTIONS=allow
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - ./grafana_data:/var/lib/grafana

  wiremock:
    image: wiremock/wiremock:latest
    container_name: wiremock
    ports:
      - '8080:8080'
    volumes:
      - ./wiremock:/home/wiremock
    command: ['--verbose', '--root-dir', '/home/wiremock']

  k6:
    image: grafana/k6
    container_name: k6
    depends_on:
      - express-api
    volumes:
      - ./loadMocking:/scripts
    command: ['run', '/scripts/k6.ts']
    restart: always
