# # Use Node.js base image
FROM node:18

# # Set working directory inside the container
WORKDIR /app

# # Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# # Copy application files
COPY . .

# # Expose port 8000 for API
EXPOSE 3001

# # Start the API Gateway
CMD ["npm", "run", "dev"]
